version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-net

  app:
    build:
      context: .
    env_file:
      - .env
    environment:
      DB_HOST: db  # This should be the service name of the db container
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgres-data:
